import os
import re

js_file = r"c:\Users\hp\OneDrive\Desktop\eventra india\js\events.js"

new_data = """    const MASTER_EVENT_DATA = [
        {
            id: "ev-001",
            title: "Sunburn Festival Goa",
            description: "Asia's premier electronic dance music extravaganza featuring global headliners on the sands of Vagator.",
            category: "Music",
            city: "Goa",
            state: "Goa",
            venue: "Vagator Beach",
            date: "2026-12-28",
            time: "16:00",
            price: 4999,
            rating: 4.9,
            reviews: 1420,
            image: "../assets/images/events/goa/sunburn-festival/1.webp",
            featured: true,
            trending: true,
            organizer: "Percept Live",
            capacity: 50000,
            availableTickets: 3200,
            tags: ["EDM", "Beach", "Festival", "Nightlife"]
        },
        {
            id: "ev-002",
            title: "Durga Puja Kolkata",
            description: "Experience the vibrant colors, majestic pandals, and profound devotion of Kolkata's biggest cultural festival.",
            category: "Cultural",
            city: "Kolkata",
            state: "West Bengal",
            venue: "Citywide Pandals",
            date: "2026-10-15",
            time: "08:00",
            price: 0,
            rating: 5.0,
            reviews: 8500,
            image: "../assets/images/events/kolkata/durga-puja/1.webp",
            featured: true,
            trending: true,
            organizer: "Community Committees",
            capacity: 500000,
            availableTickets: 500000,
            tags: ["Culture", "Festival", "Heritage"]
        },
        {
            id: "ev-003",
            title: "Jaipur Literature Festival",
            description: "The greatest literary show on Earth, gathering minds, writers, and thinkers in the pink city.",
            category: "Literature",
            city: "Jaipur",
            state: "Rajasthan",
            venue: "Diggi Palace",
            date: "2026-01-20",
            time: "10:00",
            price: 1500,
            rating: 4.8,
            reviews: 3200,
            image: "../assets/images/events/jaipur/jaipur-literature-festival/1.webp",
            featured: true,
            trending: false,
            organizer: "Teamwork Arts",
            capacity: 10000,
            availableTickets: 1500,
            tags: ["Books", "Art", "Speakers"]
        },
        {
            id: "ev-004",
            title: "Delhi Comic Con",
            description: "India's greatest pop culture experience! Cosplay, merch, artists, and exclusive fan events.",
            category: "Pop Culture",
            city: "Delhi NCR",
            state: "Delhi",
            venue: "NSIC Grounds, Okhla",
            date: "2026-12-05",
            time: "11:00",
            price: 899,
            rating: 4.7,
            reviews: 4100,
            image: "../assets/images/events/delhi/comic-con-delhi/1.webp",
            featured: false,
            trending: true,
            organizer: "Comic Con India",
            capacity: 25000,
            availableTickets: 5000,
            tags: ["Comics", "Cosplay", "Anime"]
        },
        {
            id: "ev-005",
            title: "NH7 Weekender Pune",
            description: "The happiest music festival in India bringing together diverse artists across multiple genres.",
            category: "Music",
            city: "Pune",
            state: "Maharashtra",
            venue: "Mahalakshmi Lawns",
            date: "2026-11-25",
            time: "15:00",
            price: 2999,
            rating: 4.8,
            reviews: 2900,
            image: "../assets/images/events/pune/nh7-weekender-pune/1.webp",
            featured: true,
            trending: true,
            organizer: "OML",
            capacity: 30000,
            availableTickets: 2000,
            tags: ["Music", "Live", "Festival"]
        },
        {
            id: "ev-006",
            title: "Bengaluru Food Fete",
            description: "A colossal gathering of Bengaluru's best eateries, food trucks, and culinary innovators.",
            category: "Food",
            city: "Bengaluru",
            state: "Karnataka",
            venue: "KTPO Whitefield",
            date: "2026-04-10",
            time: "12:00",
            price: 299,
            rating: 4.6,
            reviews: 1800,
            image: "../assets/images/events/bengaluru/bengaluru-food-fete/1.webp",
            featured: false,
            trending: true,
            organizer: "Foodies Inc",
            capacity: 15000,
            availableTickets: 4000,
            tags: ["Food", "Culinary", "Family"]
        },
        {
            id: "ev-007",
            title: "International Kite Festival",
            description: "Experience the skies of Ahmedabad come alive with millions of colorful kites during Uttarayan.",
            category: "Cultural",
            city: "Ahmedabad",
            state: "Gujarat",
            venue: "Sabarmati Riverfront",
            date: "2026-01-14",
            time: "08:00",
            price: 100,
            rating: 4.9,
            reviews: 5000,
            image: "../assets/images/events/ahmedabad/international-kite-festival/1.webp",
            featured: true,
            trending: true,
            organizer: "Gujarat Tourism",
            capacity: 100000,
            availableTickets: 20000,
            tags: ["Festival", "Heritage", "Family"]
        },
        {
            id: "ev-008",
            title: "Chennai Marathon",
            description: "Join thousands of runners in one of India's largest and most vibrant city marathons.",
            category: "Sports",
            city: "Chennai",
            state: "Tamil Nadu",
            venue: "Marina Beach",
            date: "2026-01-05",
            time: "04:00",
            price: 1200,
            rating: 4.7,
            reviews: 3100,
            image: "../assets/images/events/chennai/chennai-marathon/1.webp",
            featured: false,
            trending: false,
            organizer: "Chennai Runners",
            capacity: 25000,
            availableTickets: 1000,
            tags: ["Running", "Sports", "Fitness"]
        },
        {
            id: "ev-009",
            title: "Numaish Exhibition Hyderabad",
            description: "The historic All India Industrial Exhibition showcasing goods, rides, and food from across the country.",
            category: "Exhibition",
            city: "Hyderabad",
            state: "Telangana",
            venue: "Exhibition Grounds",
            date: "2026-02-01",
            time: "16:00",
            price: 50,
            rating: 4.8,
            reviews: 6200,
            image: "../assets/images/events/hyderabad/numaish-exhibition/1.webp",
            featured: true,
            trending: true,
            organizer: "AIIE Society",
            capacity: 100000,
            availableTickets: 50000,
            tags: ["Shopping", "Fair", "Family"]
        }
    ];"""

with open(js_file, 'r', encoding='utf-8') as f:
    content = f.read()

# regex to replace from "const MASTER_EVENT_DATA = [" to the closing "];" before window.EventApp
pattern = re.compile(r'const MASTER_EVENT_DATA = \[\s*\{.*?\}\s*\];', re.DOTALL)
new_content = pattern.sub(new_data, content)

with open(js_file, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Events replaced!")
